service:
  name: gateway
  port: 8080

image:
  repository: shadowxtof/bmstu-semester_9-rsoi-lab4-gateway
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ingress:
  host: "ticketbuy.ru"
  
data:
  DATABASE_URL: "postgresql://program:test@postgres-postgresql.default.svc.cluster.local:5432/flights"
  BONUS_SERVICE: "bonuses-ticketbuy"
  FLIGHT_SERVICE: "flights-ticketbuy"
  TICKET_SERVICE: "tickets-ticketbuy"