name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0



      # TODO build, publish to docker hub, deploy to k8s
      # - name: UnitTests
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.10"
      # - run: |
      #     docker compose up postgres -d
      #     pip install -r requirements.txt
      #     export DATABASE_URL="postgresql://program:test@localhost:5432/flights"
      #     pytest app/FlightService/tests.py
      #     export DATABASE_URL="postgresql://program:test@localhost:5432/tickets"
      #     pytest app/TicketService/tests.py
      #     export DATABASE_URL="postgresql://program:test@localhost:5432/privileges"
      #     pytest app/BonusService/tests.py
      #     docker compose down

      # - uses: docker/setup-buildx-action@v2 
      # - name: Build images
      #   timeout-minutes: 10
      #   run: docker compose build
      
      - name: Set up k8s
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.16.4'

      - name: Install Yandex Cloud CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH
          echo "Yandex Cloud CLI installed and added to PATH"

      - name: Publishing
        timeout-minutes: 10
        env:
          YC_SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          

          sudo bash -c "echo '84.201.149.237 ticketbuy.ru' >> /etc/hosts"

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v1/postman/collection.json
          environment: v1/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 5
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"